### ISSUE TITLE
Failed Error

### ISSUE THREAD

**Issue by aguilar1181** [katzwebservices/Contact-Form-7-Newsletter#33]
I keep getting this message any ideas

"Failed to send your message. Please try later or contact the administrator by another method."
You can see it at www.galeo.org

**Comment by uberkb** [comment]
I just ran into this issue. The form was working for about a day. Now it's not working, and I haven't touched a thing. Does anyone know any replacement plugins that work well? I've been avoiding trying to find one because when this works, it integrates well with CF7. It's no longer reliable enough.

**Comment by aguilar1181** [comment]
I'm just using the constant contact plugin now.

https://wordpress.org/plugins/constant-contact-api/

**Comment by zackkatz** [comment]
If you modify the `nameparse.php` file and change the first line from `<?` to `<?php`, it should fix this issue.

The fix will be included in the next release, coming soon.
