### ISSUE TITLE
Contacts not being sent to Constant Contact

### ISSUE THREAD

**Issue by jeneenj** [katzwebservices/Contact-Form-7-Newsletter#38]
I'm having the same problem a number of other people are having. My Contact Form 7 forms work fine, and send me the emails, but the information is not being sent to Constant Contact. Wordpress and plugins are all updated. Any help would be appreciated, as this was the perfect solution for my site when it worked.

**Comment by interactiveoms** [comment]
I am having the same issue using Version: 2.0.6.3 and Version 4.1 of Contact Form 7 with WordPress 4.1.1. 

Can someone help me figure out why?

**Comment by darrennye** [comment]
Same issue. The forms are working and emailing. My login from the plugin to constant contact via the admin appears to be working. Success in sending the form to my email. But not being pushed to constant contact and no errors.

**Comment by zackkatz** [comment]
This should be fixed in the latest update (2.1). Please let me know if not.
