### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by vorddss** [katzwebservices/Contact-Form-7-Newsletter#41]
Hi Team,

I tried to install install version 2.0.6.3 with wordpress version 4.1 and getting error while adding username and password page -
Fatal error: Call to undefined function curl_init() in /imedia/users/JG4/htdocs/wp-content/plugins/contact-form-7-newsletter/api/ctctWrapper.php on line 161

Please help me to remove this error.

Thanks,
Anup

**Comment by zackkatz** [comment]
Have your host activate `curl`. That'll fix it.

**Comment by vorddss** [comment]
Yes, it works now.! Thanks.
