### ISSUE TITLE
Not submitting to constant contact

### ISSUE THREAD

**Issue by thesius** [katzwebservices/Contact-Form-7-Newsletter#45]
Plugin is not submitting to constant contact the contact information from the form. The lists pull in which seems to show that it is pulling from my account but not sending. 

Any help appreciated.

**Comment by darrennye** [comment]
Same issue described in a ticket below.

**Comment by zackkatz** [comment]
This should be fixed in the latest update (2.1). Please let me know if not.

**Comment by darrennye** [comment]
Zack,

I upgraded to 2.1.1 and tested my "Contact" form. Although the Settings show that the login is OK, the new email addresses are not being added to Constant Contact.

If you'd like to login to investigate, please do. I believe I emailed you my login details. Or contact me via nye@nyetech.com
