### ISSUE TITLE
The requested URL returned error: 400 Bad Request

### ISSUE THREAD

**Issue by vishalbhisara** [katzwebservices/Contact-Form-7-Newsletter#46]
I have Update the wordpress version after not insert any contact in my Constant contact list.

My current wordpress version is 4.1.1, Contact Form 7 version is 4.1.1 and Contact Form 7 Newsletter version is 2.0.6.3.

I have debug code and find the below error.

Please help me. :)

Array
(
    [xml] => 
    [info] => Array
        (
            [url] => https://api.constantcontact.com/ws/customers/MyAccountID/contacts
            [content_type] => 
            [http_code] => 400
            [header_size] => 25
            [request_size] => 337
            [filetime] => -1
            [ssl_verify_result] => 0
            [redirect_count] => 0
            [total_time] => 0.268361
            [namelookup_time] => 3.7E-5
            [connect_time] => 0.045446
            [pretransfer_time] => 0.140475
            [size_upload] => 1522
            [size_download] => 0
            [speed_download] => 0
            [speed_upload] => 5671
            [download_content_length] => -1
            [upload_content_length] => 1522
            [starttransfer_time] => 0.18234
            [redirect_time] => 0
            [certinfo] => Array
                (
                )
            [redirect_url] => 
        )

    [error] => The requested URL returned error: 400 Bad Request
)

**Comment by zackkatz** [comment]
This should be fixed in the latest update (2.1). Please let me know if not.
