### ISSUE TITLE
Crowd-funded update to work with WP 4.0+?

### ISSUE THREAD

**Issue by ivandurst** [katzwebservices/Contact-Form-7-Newsletter#49]
@zackkatz - are you still supporting this plugin? I haven't seen a response to any of the questions regarding the plugin breaking in WP 4+. Do you have any beta code, or has anyone forked and successfully patched the plugin? WP 4.0 was released early September - nearly 9 months ago - and I can't find a single mention of an upgrade even being on the road map. This is not a difficult patch afaik - can you give us some insight as to what the struggle is? I'd be happy so set up a crowd-funding campaign if you'd like to see some $$ for your efforts, just let me know what the total dollar amount you're looking for is and we'll make it happen. 

I've been using CF7 for years and still think it's the best WP form plugin available - I do not mean to sound ungrateful, I am in fact very grateful for your hard work and contribution to the community. But rolling back to a WP version that's coming up on a year old and is full of security holes is not an option... _please_ give us a response, something to work with, even if it's just a few words. Anything. Just answer the community.

**Comment by Blenderman18** [comment]
I would be willing to contribute as well. We have been using this plugin for years and really don’t want to figure out another option. It used to work so well.

**Comment by zackkatz** [comment]
Hi @ivandurst and @Blenderman18 - thanks for writing in. I actually was going to have @luistinygod tackle some of these issues next week. It's been busy!

Any contributions would be appreciated—please donate some bucks to a charity of your choice :+1: We'll be working on these tickets soon.

Sorry for the delay.

**Comment by Blenderman18** [comment]
Do you do work for hire. I tried contacting you before about paying you to help with an issue I was having with your plugin and wordpress.

**Comment by zackkatz** [comment]
Sorry, no. I recommend using Codeable.io to fix the issue, then submitting a pull request here on Github.
