### ISSUE TITLE
integration with Akismet

### ISSUE THREAD

**Issue by michaelhauser** [katzwebservices/Contact-Form-7-Newsletter#5]
Thanks for the plugin. I have it working successfully with Constant Contact, but I added Akismet options to the form and tried submitting the viagra spam test and it doesn't get filtered. Here's my form:

[text\* first-name 20/40 akismet:author placeholder "First Name"][text\* last-name  20/40 akismet:author placeholder "Last Name"][email\* email-address 20/40 akismet:author_email placeholder "Email"][submit "Join"]

The selected integration fields are email, first-name, and last-name. The form is at http://milkgenomics.org in the footer. Any ideas? Thanks.

**Comment by whynotadv** [comment]
I posted my own issue a few minutes ago Nov 14, 2016 and searched and found this thread where you were talking about Spam so I thought I'd post here also. I have no idea why my client is receiving spam submissions here: http://www.runkles.com look at the bottom right corner Subscribe to newsletter form with reCaptcha.
