### ISSUE TITLE
Contact form 7 V4.2

### ISSUE THREAD

**Issue by ajiseco** [katzwebservices/Contact-Form-7-Newsletter#51]
This version of contact form 7 changed the form editor, so now there are no way to edit each from lists.

Are there any fixes for this?

**Comment by jberg1** [comment]
Same problem.
Just updated my Contact Form 7 Plugin (changed the interface), and now I have a problem with the Constant Contact Contact Form 7 Newsletter.

When I edit the form I get a button that has code in it
<img src="http://www.domainname.com/wp-content/plugins/contact-form-7-newsletter/favicon.png" width="16" height="16" alt="" /> Constant Contact Lists
And when I click the button I just get an empty pop-up with the title
Form-tag Generator: Constant Contact Lists

Thanks for any help on a fix

**Comment by actionbasic** [comment]
Same issue as jberg1. And crucial unfortunately. Any fix for this?

**Comment by zackkatz** [comment]
I'm working on it. Stay tuned!

**Comment by zackkatz** [comment]
Alright, the update is live! Check it out :+1:
