### ISSUE TITLE
Version 2.1 Update fail

### ISSUE THREAD

**Issue by jberg1** [katzwebservices/Contact-Form-7-Newsletter#53]
Thanks for updating the plugin. However, it didn't work for me. When I updated, now I see a notification message saying I need to update Contact Form 7 to version 4.2 (which it is updated). And so I don't see any of the Constant Contact functionality on Contact Forms, and the shortcode just shows up on the form from the front-end.

I went back to the old version, and it is working on the form. But still have the same issue when editing the form. Any ideas?

**Comment by zackkatz** [comment]
Thanks for letting me know—I just updated to 2.1.1, which fixes this issue. Please update and let me know how it goes.

**Comment by jberg1** [comment]
Perfect! Thanks Zack
(sorry to reopen this)
