### ISSUE TITLE
Forms with multiple check-boxes are not received by Constant Contact

### ISSUE THREAD

**Issue by darrennye** [katzwebservices/Contact-Form-7-Newsletter#60]
I have the following forms running:
http://www.villagerstheatre.com/volunteer/signup/technical/
http://www.villagerstheatre.com/volunteer/signup/general/

The problem is if a user selects multiple check-boxes, the form does not seem to submit to Constant Contact. If they only select 1, it works fine.

Form contents are pasted below.

Any suggestions?

<p>Which Creative/Leadership roles are you interested in?<br />
[checkbox role-creative "Producer" "Director" "Assistant Director" "Musical Director" "Choreographer" "Stage Manager"]</p>

<p>Which Design roles are you interested in?<br />
[checkbox role-design "Set Designer" "Scenic Designer/Artist" "Lighting Designer" "Sound Designer" "Costume Designer"]</p>

<p>Which Technical Staff roles are you interested in?<br />
[checkbox role-tech "Assistant Stage Mgr - Production Assistant" "Technical Director" "Set Carpenter - Builder" "Set Dresser" "Lighting Board Operator" "Sound Board Operator" "Prop Coordinator - Master" "Costume Coordinator" "Hair - Makeup Artist" "Stage Hand"]</p>

<p>Your First Name (required)<br />
    [text* first-name akismet:author] </p>

<p>Your Last Name (required)<br />
    [text* last-name akismet:author] </p>

<p>Your Email (required)<br />
    [email* email akismet:author_email] </p>

<p>Are you an adult? (required)<br />
   [radio age "Under 18" "18 or Older"] </p>

<p>Home Street Address 1<br />
    [text street-address1] </p>
<p>Home Street Address 2<br />
    [text street-address2] </p>

<p>City<br />
    [text city] </p>

<p>State<br />
    [text state] </p>

<p>Zip<br />
    [text zip] </p>

<p>Home Number<br />
    [text phone-number] </p>

<p>Mobile Number<br />
    [text mobile-phone] </p>

<p>Mobile Carrier (to receive txt msgs)<br />
    [select mobile-carrier include_blank "verizon" "att" "sprint" "tmobile" "metropcs" "nextel" "qualcom" "googlevoice" "other"] </p>

<p>Additional Comments?<br />
    [textarea message] </p>

<p>Captcha Image<br />
    [captchac captcha-256] </p>

<p>To prove you're human, type the Captcha characters seen above<br />
    [captchar captcha-256] </p>

<p>[ctct ctct-292 default:on type:checkboxes label:Add+your+info+to+our+email+lists 'Villagers News (Shows, Programs, Events)::#1' 'Technical Volunteer Opportunities::#6']

<p><strong><font color="red">Before leaving this page, please wait till you are prompted that your message was sent successfully!</font></strong></p>

<p>[submit "Submit"]</p>

**Comment by tampaaaron** [comment]
Pardon me for my ignorance, but how do you unsubscribe from notifications
for all topics for a project?

On Tue, Sep 8, 2015 at 3:46 PM, darrennye <notifications@github.com> wrote:

> I have the following forms running:
> http://www.villagerstheatre.com/volunteer/signup/technical/
> http://www.villagerstheatre.com/volunteer/signup/general/
>
> The problem is if a user selects multiple check-boxes, the form does not
> seem to submit to Constant Contact. If they only select 1, it works fine.
>
> Form contents are pasted below.
>
> Any suggestions?
>
> Which Creative/Leadership roles are you interested in?
> [checkbox role-creative "Producer" "Director" "Assistant Director"
> "Musical Director" "Choreographer" "Stage Manager"]
>
> Which Design roles are you interested in?
> [checkbox role-design "Set Designer" "Scenic Designer/Artist" "Lighting
> Designer" "Sound Designer" "Costume Designer"]
>
> Which Technical Staff roles are you interested in?
> [checkbox role-tech "Assistant Stage Mgr - Production Assistant"
> "Technical Director" "Set Carpenter - Builder" "Set Dresser" "Lighting
> Board Operator" "Sound Board Operator" "Prop Coordinator - Master" "Costume
> Coordinator" "Hair - Makeup Artist" "Stage Hand"]
>
> Your First Name (required)
> [text* first-name akismet:author]
>
> Your Last Name (required)
> [text* last-name akismet:author]
>
> Your Email (required)
> [email* email akismet:author_email]
>
> Are you an adult? (required)
> [radio age "Under 18" "18 or Older"]
>
> Home Street Address 1
> [text street-address1]
>
> Home Street Address 2
> [text street-address2]
>
> City
> [text city]
>
> State
> [text state]
>
> Zip
> [text zip]
>
> Home Number
> [text phone-number]
>
> Mobile Number
> [text mobile-phone]
>
> Mobile Carrier (to receive txt msgs)
> [select mobile-carrier include_blank "verizon" "att" "sprint" "tmobile"
> "metropcs" "nextel" "qualcom" "googlevoice" "other"]
>
> Additional Comments?
> [textarea message]
>
> Captcha Image
> [captchac captcha-256]
>
> To prove you're human, type the Captcha characters seen above
> [captchar captcha-256]
>
> [ctct ctct-292 default:on type:checkboxes
> label:Add+your+info+to+our+email+lists 'Villagers News (Shows, Programs,
> Events)::#1
> <https://github.com/katzwebservices/Contact-Form-7-Newsletter/issues/1>'
> 'Technical Volunteer Opportunities::#6
> <https://github.com/katzwebservices/Contact-Form-7-Newsletter/issues/6>']
>
> *Before leaving this page, please wait till you are prompted that your
> message was sent successfully!*
>
> [submit "Submit"]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/katzwebservices/Contact-Form-7-Newsletter/issues/60>.
>



-- 
Aaron Weiss
Senior SEO Strategist
aaron@tampa-seo.com
1-877-736-7361 x705
Website <http://www.tampa-seo.com/> | Twitter
<https://twitter.com/TampaSEOTrainer> | Facebook
<https://www.facebook.com/TampaSEOTraining> | Google+
<https://plus.google.com/+Tampa-seo> | Meetup
<http://www.meetup.com/SEO-Training-Tampa/>

**Comment by zackkatz** [comment]
@tampaaaron Click the eye at the top of GitHub and choose "Unwatch"

**Comment by zackkatz** [comment]
@darrennye This is fixed in the next update. Thanks for reporting.
