### ISSUE TITLE
Alert about navigating away from form before saving and checkbox/radio not showing up on front end

### ISSUE THREAD

**Issue by hoppities** [katzwebservices/Contact-Form-7-Newsletter#61]
The title pretty much sums it up.

My Constant Contact Newsletter checkboxes are not showing up, and when the plugin is activated, CF7 says I'm navigating away without saving, even though it is saved. When I inspect the code, I don't see anything where the shortcode should be.

I did a little testing, and `$tag->name` is returning empty in `shortcode_handler()`. Any thoughts why that might happen?

**Comment by zackkatz** [comment]
This is fixed in the next update—CF7 changed how they parse shortcodes. Sorry for the inconvenience. Please see this thread for answers: https://wordpress.org/support/topic/plugin-doesnt-work-100?replies=7#post-7594342
