### ISSUE TITLE
Contact Form 7 4.3 and Contact Form Newsletter 2.1.1 Not working

### ISSUE THREAD

**Issue by kevmcp** [katzwebservices/Contact-Form-7-Newsletter#62]
Hello, I am using Contact Form 7 4.3 and Contact Form Newsletter 2.1.1 on Wordpress 4.3.1. The forms work fine as far as sending info to the us and a response to the user. However, Constant Contact is not being updated. I have followed all the instructions and I am connected to constant contact and have inserted the code into the emails as directed. If you need any screenshots of anything, I can provide them to you. Thank you!

**Comment by rik113** [comment]
I am experiencing the same thing.

**Comment by ZoranArambasik** [comment]
Same thing here.

**Comment by Bradsap** [comment]
Yes, same thing is happening for a couple of sites I manage. Can you please provide an update on this asap? Is it something you are actively working on?

**Comment by kevmcp** [comment]
Guys, there never seems to be an answer to this issue..I switched to Gravity Forms and Gravity Forms Constant Contact Add-on, and it all works PERFECTLY, as well as giving you the option to feed the date of the form into CC....

http://www.gravityforms.com/

So worth the money, easy to set up and customize

**Comment by petermjames** [comment]
It doesn't work for me either.  This is a new site I am building.  Fortunately, it seems to be working on old sites still.  Constant Contact integration is simply too difficult and unreliable on WordPress.

**Comment by uptownlukem** [comment]
Are the plugin developers even checking these? They have a big note on the Wordpress plugin page to post all issues here, but I haven't seen one response from them for a while.

**Comment by ZoranArambasik** [comment]
No they are not for a long time. I suggest you use gravity forms as suggested above.
It worked perfectly for me.

**Comment by petermjames** [comment]
Unfortunately, the Gravity Forms add-on for Constant Contact is written by the same guy and this doesn't fill me with confidence.

**Comment by zackkatz** [comment]
I'm releasing an update with fixes soon. Please stay tuned.
