### ISSUE TITLE
Isn't working, opt-in field isn't even showing

### ISSUE THREAD

**Issue by Milbergs** [katzwebservices/Contact-Form-7-Newsletter#65]
**Wordpress** Version 4.4
**Contact Form** Version 4.3.1
**Contact Form 7 Newsletter** Version 2.1.1

I have installed the plugin and configure the settings as described, but your plugin isn't working. 

I have added the field to the form and **it even isn't show up in site (front-end)** - 
```
[ctct ctct-482 type:single label:Sign+me+up+for+your+newsletter 'General Interest::#1720680720' subscribe_type_radio:single]
```

Here is the link to form - http://www.kirkjewelers.com/watch/patek-philippe/patek-philippe-5146r-001/

I am attaching a few screenshots of the settings

![smsm8fcfop-nj_doxpyyzagzmtm1juhwfp0cpuqauug](https://cloud.githubusercontent.com/assets/2249362/11874635/728ac8f6-a4e9-11e5-895e-748180dbfc57.png)
![u5boz9um7s-1zzoeul-oaqdzcns3bjbhpmctwyfs-fe](https://cloud.githubusercontent.com/assets/2249362/11874634/728a851c-a4e9-11e5-8977-ecb10294e8fe.png)
![slbhaub9lwykjyg_bovv1_osh8g05s9r5q9qtpwq1eg](https://cloud.githubusercontent.com/assets/2249362/11874637/728e4634-a4e9-11e5-9879-0f91cbc3d25d.png)
![mslcfogfyu0gojkkkgoywomcnnrc0wnb6rxclfcofps](https://cloud.githubusercontent.com/assets/2249362/11874636/728d5af8-a4e9-11e5-8cca-88e638edf9d4.png)

**Comment by roydezign** [comment]
Its not working for me either, Contact Form 4.3.1 and Contact Form 7 Newsletter 2.1.1

**Comment by Milbergs** [comment]
I have already found solution with different plugin, closing this!

**Comment by Blenderman18** [comment]
What plugin are you using.
