### ISSUE TITLE
Plugin causing 500 error on form submission; email goes through but infinite spinner

### ISSUE THREAD

**Issue by cobblehillmachine** [katzwebservices/Contact-Form-7-Newsletter#74]
I was so excited to find this plugin, hopefully can resolve this issue! When the plugin is activated, Contact Form 7 submission still come through to my email but the spinner never stops and checking the network, shows a 500 error. Deactivating the plugin solves. Error log shows the following:

[Thu Aug 11 11:17:57.821087 2016] [:error] [pid 11406] [client 50.150.42.16:58111] PHP Fatal error:  Uncaught Error: Call to undefined function simplexml_load_string() in /wp-content/plugins/contact-form-7-newsletter/api/ctctWrapper.php:988\nStack trace:\n#0 /wp-content/plugins/contact-form-7-newsletter/cf7-constantcontact.php(768): CTCTContactsCollection->searchByEmail('maryhipp@gmail....')\n#1 /wp-includes/plugin.php(525): CTCTCF7->process_submission(Object(WPCF7_ContactForm))\n#2 /wp-content/plugins/contact-form-7/includes/submission.php(163): do_action('wpcf7_mail_sent', Object(WPCF7_ContactForm))\n#3 /wp-content/plugins/contact-form-7/includes/submission.php(28): WPCF7_Submission->submit()\n#4 /wp-content/plugins/contact-form-7/includes/contact-form.php(617): WPCF7_Submission::get_instance(Object(WPCF7_ContactForm))\n#5 /wp-content/plugins/contact-f in /wp-content/plugins/contact-form-7-newsletter/api/ctctWrapper.php on line 988, referer: http://drann.cobblehilldigital.com/contact/

Running WordPress v4.5.3, Contact Form 7 v4.5, Contact Form 7 Newsletter v2.2. Thank you!!!

**Comment by zackkatz** [comment]
Ask your host to install the SimpleXML PHP library and that'll fix the issue.
