### ISSUE TITLE
Client is Receiving Spam Subscribers to Their Constant Contact List

### ISSUE THREAD

**Issue by whynotadv** [katzwebservices/Contact-Form-7-Newsletter#77]
Not sure what to do, my client is receiving tons of spam email subscriptions. I scanned the website and it does not have Malware and it has not been hacked and is on the latest version of Wordpress. All other plugins are up-to-date. I also further tightened security with a Google ReCaptcha and the client is still receiving spam submissions (100s a day) what can be done?? http://www.runkles.com is where the form with Constant Contact is located bottom right corner of the home page. Any urgent help you can provide would be great. The site is self-hosted on a Windows Server IIS.

Thanks,
Kenny

**Comment by zackkatz** [comment]
The plugin only processes after the submission is validated by Contact Form 7; the submissions aren't being caught as spam there.
