### ISSUE TITLE
Custom field names not matching what's in Constant Contact

### ISSUE THREAD

**Issue by ponchohoncho** [katzwebservices/Contact-Form-7-Newsletter#80]
I have several fields I want to match to Custom Fields in Constant Contact. I have given them unique names there (Child's Name, Teacher, etc), but they're just listed as "Custom Field 1", 2, 3 etc in the plugin UI. When the form is submitted, the existing fields are ignored and new "Custom Field 1" 2, 3 etc are made.

**Comment by ponchohoncho** [comment]
Looks like this is an issue with the Constant Contact API itself. Bummer. https://github.com/constantcontact/php-sdk/issues/29

**Comment by zackkatz** [comment]
Yep, 'fraid it is…I wish it weren't the case.

**Comment by zagarskas** [comment]
Its been years now... is this still a problem? it is for me... still stuck using "CustomField1" and "CustomField2" instead of **super important sane human words like** "Signup Source" and "Industry Interest"
