### ISSUE TITLE
Contact Form 7 adds new contacts to Constant Contact incorrectly for new campaign

### ISSUE THREAD

**Issue by mkdevicepharm** [katzwebservices/Contact-Form-7-Newsletter#82]
Our site uses Contact Form 7 to integrate our site with Constant Contact, so if a new user fills out the contact form on our site, their information will automatically be updated in our Constant Contact account. Our Constant Contact is then set up to send a welcome email drip campaign out to all new contacts as they are added. However, based on how Contact Form 7 adds contacts to our system, it’s adding them as being added by the account owner in Constant Contact, which won’t trigger the welcome email drip campaign that has been set up. Is it possible to modify how Contact Form 7 adds the new contacts so that Constant Contact will recognize them as not added by the account owner? Thank you!

**Comment by zackkatz** [comment]
If there's an `accept` field to allow the user to opt in, it'll show by the user. Otherwise, no way currently.
